### ISSUE TITLE
Errors when building with Cesium for Unreal 1.8.1

### ISSUE THREAD

**Issue by fortek12** [SquarerFive/cesium-procedural-foliage#2]
![Cesium_Procedural_Foliage_Build-Errors](https://user-images.githubusercontent.com/21313041/145518020-45ef4756-b817-44ab-9e99-02ab695dfaed.png)

I am seeing the attached errors when building for Cesium for Unreal 1.8.1 with Unreal Engine 4.27.X.

Cesium for Unreal updated many variable names in Cesium for Unreal 1.7 and beyond (see here: https://github.com/CesiumGS/cesium-unreal/blob/main/CHANGES.md), so I was able to fix those by updating the variable names in FoliageCaptureActor.cpp and ProceduralFoliageEllipsoid.cpp. These name updates resolved some of the constant declarations as well.

Primarily, I am unable to resolve the "'ACesium3DTileset::Georeference': cannot access private member declared in class" error satisfactorily. I tried making those private members public and it built successfully, but the foliage is still not being generated in Unreal after updating with my Cesium token.

**Comment by SquarerFive** [comment]
Hi, I've just pushed a fix for the latest version of cesium-for-unreal, foliage appears to be spawning now on my end, let me know if this works for you,

Thanks.

![image](https://user-images.githubusercontent.com/20653043/145523566-e2d2ab9b-64b9-4d0f-87a5-d539484cd4a2.png)

**Comment by fortek12** [comment]
Everything is working now. Thank you for the quick turnaround! This is some really awesome work you developed.
