### ISSUE TITLE
Small comparison bug

### ISSUE THREAD

**Issue by kebiro** [SquarerFive/cesium-procedural-foliage#3]
Just noticed there might be a little bug in `FoliageCaptureActor.cpp`. 

In the lambda function that is bound to `OnRenderTargetRead` there is this little for loop:

```cpp
UFoliageHISM* MinimumHISM = HISMFoliageMap[FoliageGeometryType][0];
for (UFoliageHISM* HISM : HISMFoliageMap[FoliageGeometryType])
{
	if (FoliageTransforms.HISMTransformMap.Contains(HISM) && FoliageTransforms.HISMTransformMap.Contains(MinimumHISM))
	{
		if (FoliageTransforms.HISMTransformMap[HISM].Num() < FoliageTransforms.HISMTransformMap[HISM].Num())
		{
			MinimumHISM = HISM;
		}
	}
}
```

Looks to me like that if condition should use `MinimumHISM` as the index to the right of the comparison operator.

**Comment by SquarerFive** [comment]
Good find! I'll include a fix in the next push
