### ISSUE TITLE
Unable to find plugin 'Bridge' (referenced via aiden_geo_tutorial.uproject). Install it and try again, or remove it from the required plugin list.	aiden_geo_tutorial	D:\2022\work\cesium-procedural-foliage-main\cesium-procedural-foliage-main\Intermediate\ProjectFiles\UnrealBuildTool

### ISSUE THREAD

**Issue by Mr-MS-Zhang** [SquarerFive/cesium-procedural-foliage#6]
Unable to find plugin 'Bridge' (referenced via aiden_geo_tutorial.uproject). Install it and try again, or remove it from the required plugin list.	aiden_geo_tutorial	D:\2022\work\cesium-procedural-foliage-main\cesium-procedural-foliage-main\Intermediate\ProjectFiles\UnrealBuildTool
我已经安装了bridge插件编译的时候还是有这个问题

**Comment by SquarerFive** [comment]
Should now be fixed on the ue4-main branch as UE4 doesn't have quixel bridge installed by default:
https://github.com/SquarerFive/cesium-procedural-foliage/tree/ue4-main
